spring.application.name=upload-to-sharepoint



onedrive.token.url=https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/token
onedrive.tenant.id=${TENANT_ID}
onedrive.client.id=${CLIENT_ID}
onedrive.pfx.path=/home/yovo/Documents/uploadToOneDrive/cert/certificate.pfx
onedrive.pfx.password=${PFX_PASSWORD}

server.servlet.session.persistent=false

onedrive.upload.url=https://graph.microsoft.com/v1.0/me/drive/root:/uploadToOneDrive.xml:/content

logging.level.org.springframework.boot=DEBUG
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.sharepoint.upload.upload_to_sharepoint.service=DEBUG
logging.level.org.apache.http=DEBUG
