spring.application.name=upload-to-sharepoint

onedrive.client.id=${CLIENT_ID}
onedrive.client.secret=${CLIENT_SECRET}
onedrive.tenant.id=${TENANT_ID}

server.servlet.session.persistent=false

onedrive.upload.url=https://graph.microsoft.com/v1.0/me/drive/root:/uploadToOneDrive.xml:/content

logging.level.org.springframework.boot=DEBUG
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.sharepoint.upload.upload_to_sharepoint.service=DEBUG
logging.level.org.apache.http=DEBUG
